### ISSUE TITLE
Why now Grafana service is type "NodePort" instead of "ClusterIp"?

### ISSUE THREAD

**Issue by luarx** [brancz/kubernetes-grafana#102]
Hi everyone!

I think that before it was "ClusterIP" type, is there any reason to use now "NodePort"?

Thanks a bunch :)

**Comment by brancz** [comment]
Thank you so much for reporting this! I think this was an accidental mistake introduced by https://github.com/brancz/kubernetes-grafana/pull/99.

@metalmatze Do you think you could have a look at this?

**Comment by brancz** [comment]
The examples intentionally set NodePorts, but I think by default this accidentally snuck in https://github.com/brancz/kubernetes-grafana/pull/99/files#diff-f5de80d55283f03a8010a56c26846b0e7cac2338e32a2458df76df107a5b7c64R172

We should be back to our previous behavior just by removing that one line I believe.

**Comment by metalmatze** [comment]
Happy to give you a change to contribute @luarx :)
