### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by mrsiano** [brancz/kubernetes-grafana#28]
Hey the following links in README are broken 
The Grafana dashboard sources configuration.
The Grafana datasources configuration.
The Grafana dashboard definitions with the help of grafana/grafonnet-lib.
The Grafana Kubernetes manifests with the help of ksonnet/ksonnet-lib.

**Comment by brancz** [comment]
Yes! You're absolutely right, sorry for the trouble, I will make sure to fix the readme in this regard.
