### ISSUE TITLE
dashboard outdated?

### ISSUE THREAD

**Issue by KlavsKlavsen** [brancz/kubernetes-grafana#37]
When grafana pods starts up it logs:
```t=2018-08-03T14:38:55+0000 lvl=warn msg="[Deprecated] the dashboard provisioning config is outdated. please upgrade" logger=provisioning.dashboard filename=/etc/grafana/provisioning/dashboards/dashboards.yaml```

**Comment by brancz** [comment]
I created #38 to fix this. Thanks for reporting!
