### ISSUE TITLE
Custom grafana.ini prevents datasources and dashboards mounts

### ISSUE THREAD

**Issue by kskewes** [brancz/kubernetes-grafana#43]
If a custom `config: ` section is defined, then the secret will be mounted at `/etc/grafana` per: https://github.com/brancz/kubernetes-grafana/blob/master/grafana/grafana.libsonnet#L88

This seems to prevent datasources and dashboardSources from being mounted under sub-directories of `/etc/grafana` as intended here:
https://github.com/brancz/kubernetes-grafana/blob/master/grafana/grafana.libsonnet#L97 

Options?
1. Add subPath to deployment for secret volume mount with [ksonnet mixin](https://github.com/ksonnet/ksonnet-lib/blob/master/ksonnet.beta.1/core.v1.libsonnet#L3919). Downside is no automatic updates on secret (config) change. eg:
```
      local configVolumeMount = containerVolumeMount.new(configVolumeName, '/etc/grafana/grafana.ini') +
                                containerVolumeMount.withSubPath('grafana.ini');
```

2. Overwrite provisioning dir, but this makes installation non standard. [grafana.ini line](https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L27)

3. Other?

**Comment by brancz** [comment]
I'm not exactly sure what the problem is, as we are using a custom `grafana.ini` in the OpenShift monitoring stack, and it works just fine with mounting the config into `/etc/grafana` and provisioning dirs into `/etc/grafana/provisioning/datasources` and `/etc/grafana/provisioning/dashboards`, as it's standard I believe.

**Comment by kskewes** [comment]
Sorry, I suspect I broke it when doing last PR (fixed by https://github.com/brancz/kubernetes-grafana/pull/46). 
I did initially change all of those configmap null lines to std.length in my work repo, but when came to upstreaming must have missed them. Then probably got caught out by own miss.. sigh. 1000 apologies.

**Comment by metalmatze** [comment]
No worries. We caught it and it's all good now. Thanks for contributing the feature. :+1:
