### ISSUE TITLE
possibility to add server certificates to grafana

### ISSUE THREAD

**Issue by wht19** [brancz/kubernetes-grafana#47]
Is it possible to add server certificates?
I can generate the correct config for grafana (see below) but how do I add the certificates themselves as secrets? I guess I have to rewrite grafana.libsonnet?

local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
{
_config+:: {
namespace: 'monitoring',
grafana+:: {
config: { // http://docs.grafana.org/installation/configuration/
sections: {
"security": {admin_password: 'supersecret'},
"server": { protocol: 'https', cert_file: 'server.crt', cert_key: 'server.key' },
},
},
},
},
};

**Comment by brancz** [comment]
jsonnet allows merging of objects, all you need to do is something along the lines of this (let's call the file `grafana-add-tls.jsonnet`):

```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local service = k.core.v1.service;
local daemonset = k.apps.v1beta2.deployment;
local container = deployment.mixin.spec.template.spec.containersType;
local volume = deployment.mixin.spec.template.spec.volumesType;
local containerVolumeMount = container.volumeMountsType;
local tlsVolumeName = 'grafana-tls';

{
  grafana+:: {
    deployment+:: {
      spec+: {
        template+: {
          spec+: {
            containers:
              std.map(
                function(c)
                  c {
                    volumeMounts: [
                      containerVolumeMount.new(tlsVolumeName, '/etc/tls/'),
                    ],
                  },
                super.containers,
              ),
            volumes+: [volume.fromSecret(tlsVolumeName, 'grafana-tls')],
          },
        },
      },
    },
  },
}
```

Then in your `main.jsonnet` you just append that:

```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +
(import 'grafana-add-tls.jsonnet')
...
```

> (side note I haven't executed the above but we do something very similar to this in our jsonnet codebase)

**Comment by wht19** [comment]
Thanks! I used your info to fix the issue. I'am a total newbie regarding jsonnet but now it works with the config below. 

"grafana-add-tls.jsonnet":

local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local service = k.core.v1.service;
local daemonset = k.apps.v1beta2.daemonset;
local deployment = k.apps.v1beta2.deployment;
local container = deployment.mixin.spec.template.spec.containersType;
local volume = deployment.mixin.spec.template.spec.volumesType;
local containerVolumeMount = container.volumeMountsType;
local tlsVolumeName = 'grafana-tls';
local secret = k.core.v1.secret;
{
  grafana+:: {
      secret:
        secret.new('grafana-tls', {
          'grafana-server-ca.crt': std.base64($._config.grafana.serverCA),
          'grafana-server.key': std.base64($._config.grafana.serverKey),
          'grafana-server.crt': std.base64($._config.grafana.serverCert),
        }) +
        secret.mixin.metadata.withNamespace($._config.namespace),
      deployment+: {
       spec+: {
         template+: {
           spec+: {
             containers:
               std.map(
                 function(c)
                   c {
                     volumeMounts+: [
                       containerVolumeMount.new(tlsVolumeName, '/etc/ssl/grafanacerts'),
                     ],
                   },
                 super.containers,
               ),
             volumes+: [volume.fromSecret(tlsVolumeName, 'grafana-tls')],
           },
         },
       },
     },
   },


And "main.jsonnet" :

local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') +
           (import 'kube-prometheus/kube-prometheus-anti-affinity.libsonnet') +  
           (import 'grafana-add-tls.jsonnet') 
 {
  _config+:: {
    namespace: 'monitoring',
     grafana+:: {
        config: { // http://docs.grafana.org/installation/configuration/
          sections: {
            "security": {admin_password: 'supersecret'},
            "server": { protocol: 'https', cert_file: '/etc/ssl/grafanacerts/grafana-server.crt', cert_key: '/etc/ssl/grafanacerts/grafana-server.key' },
          },
        },
        serverCA: importstr 'certs/grafana-server-ca.crt',
        serverKey: importstr 'certs/grafana-server.key',
        serverCert: importstr 'certs/grafana-server.crt',
      },
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
