### ISSUE TITLE
Override default jsonnet variables for storage

### ISSUE THREAD

**Issue by carlosedp** [brancz/kubernetes-grafana#54]
I'm building a jsonnet deployment for the Prometheus/Grafana stack and would like to override the default config for some of the volumeMounts.

For example the persistent storage for Grafana is an emptyDir but I would like to use a PVC. Can these variables be overwritten by my jsonnet file?

The default is:
```
local storageVolumeName = 'grafana-storage';
local storageVolume = volume.fromEmptyDir(storageVolumeName);
local storageVolumeMount = containerVolumeMount.new(storageVolumeName, '/var/lib/grafana');
```

I'd like to do something like this:

```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
...
 grafana+:: {
    deployment+:
      {
      local storageVolumeName = 'grafana-storage';
      local storageVolume = volume.withName(storageVolumeName);
      local storageVolumeMount = containerVolumeMount.new(storageVolumeName, '/var/lib/grafana');
...
},
```
Another question is if it's possible to override a mount path, like replacing `local storageVolumeMount = containerVolumeMount.new(storageVolumeName, '/var/lib/grafana');` with `local storageVolumeMount = containerVolumeMount.new(storageVolumeName, '/data');` for example.

And I make a separate PVC for this. Is it possible?
Thanks!

**Comment by carlosedp** [comment]
I saw it and based some of my customisation on the OpenShift changes. I understand is that these projects are meant to be extended as well.

In my case, I'd like to override the variables so I can have persistence for Grafana in case the Pod dies or get rescheduled.

**Comment by brancz** [comment]
@metalmatze is right. The whole point of this project is to have Grafana be 100% declaratively configured. That way PVC is not necessary, as a new instance will be consistently configured anyways.

**Comment by carlosedp** [comment]
Actually, the persistence is important since any created user, set passwords, notification configs are lost in case Grafana pod gets killed.

I managed to override the config on the jsonnet file to have a PVC:

```
    grafana+:: {
        deployment+: {
            spec+: {
            template+: {
                spec+: {
                volumes:
                    std.map(
                        function(v)
                            if v.name == 'grafana-storage' then
                            {'name':'grafana-storage',
                                'persistentVolumeClaim': {
                                    'claimName': 'grafana-storage'}
                            }
                            else
                                v,
                    super.volumes
                    ),
                },
            },
            },
        },
        storage:
            local pvc = k.core.v1.persistentVolumeClaim;
            local deployment = k.apps.v1beta2.deployment;
            pvc.new() + pvc.mixin.metadata.withNamespace($._config.namespace) +
                        pvc.mixin.metadata.withName("grafana-storage") +
                        pvc.mixin.spec.withAccessModes('ReadWriteMany') +
                        pvc.mixin.spec.resources.withRequests({ storage: '2Gi' }),
    },
```

**Comment by metalmatze** [comment]
We want this setup to be completely stateless and not save anything to disk, but rather use another login provider: http://docs.grafana.org/auth/overview/#oauth-integrations

Of course, that is the beauty of jsonnet, you can still override / extend it as you have done above.

**Comment by carlosedp** [comment]
I've put this just for future reference in case anyone looks for it. Thanks for the clarification @metalmatze .

**Comment by blandflakes** [comment]
Just to clarify - you'll want a PVC if you want to save anything the user has customized, like starred dashboards, homepages, etc. While using another auth provider reduces state, obliterating the database still loses important user data.

**Comment by carlosedp** [comment]
@blandflakes that's exacly why I'm overriding this on my monitoring stack here: https://github.com/carlosedp/cluster-monitoring/blob/12dd5665b0ec81bbaf7e00e434ae18d10311b193/base_operator_stack.jsonnet#L87

**Comment by blandflakes** [comment]
Your example was helpful! Unfortunately, I don't have access to a PVC storage class on GKE that supports ReadWriteMany, so if I ever have more than one Grafana pod, I can't share the database.

My plan is to configure Grafana to talk to a Postgres instance instead.

**Comment by kunickiaj** [comment]
> We want this setup to be completely stateless and not save anything to disk, but rather use another login provider: http://docs.grafana.org/auth/overview/#oauth-integrations
> 
> Of course, that is the beauty of jsonnet, you can still override / extend it as you have done above.

Even using an external login provider, seeding Teams is not available in the OSS version, so I don't really see an option outside of PVC / Database, do you?
