### ISSUE TITLE
Question on using secret for admin username/password

### ISSUE THREAD

**Issue by fritchie** [brancz/kubernetes-grafana#62]
General question:

Would it be possible to have the admin username/password stored in a secret that is loaded in the grafana container env, ie:

env:
- name: GF_SECURITY_ADMIN_USER
  valueFrom:
    secretKeyRef:
      key: admin-user
      name: grafana-admin
- name: GF_SECURITY_ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      key: admin-password
      name: grafana-admin

**Comment by metalmatze** [comment]
The Grafana config that configures the mixin is converted to a Kubernetes Secret object.
Use should be able to simply put your user and password there to end up with the same result, that you are asking about.

**Comment by fritchie** [comment]
I was actually thinking about using an existing secret in etcd and modifying the container environment in the deployment to use it.

**Comment by brancz** [comment]
This will need to trigger a redeploy which changing the secret referenced in the env variable does not do.

**Comment by fritchie** [comment]
thx
