### ISSUE TITLE
How do I add service metadata annotations?

### ISSUE THREAD

**Issue by jpc2350** [brancz/kubernetes-grafana#65]
I'm using this through the kube-prometheus jsonnet library (as intended and recommended in the Readme), but it lacks the documentation of adding annotation metadata to services, for example using external-dns as follows:

```apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <my hostname>
```

How can this be done, whilst at the same time being able to us jb update etc?

At the moment, the only way I can successfully see to do this would be to add 
`service.mixin.metadata.withAnnotations($._config.grafana.annotations),`
to vendor/grafana/grafana.libsonnet, but that would mean that the change would get overwritten when we run jb update

**Comment by metalmatze** [comment]
This is really a kube-prometheus question then, but here's the answer. By using composition you can extend the provided objects with whatever you want to add.
You probably want to copy the [example.jsonnet](https://github.com/coreos/kube-prometheus/blob/master/example.jsonnet) for you own project and then make the additional changes there.

Here's the change to add the annotations to the Grafana Service.

```diff
+local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
+local service = k.core.v1.service;
+
 local kp =
   (import 'kube-prometheus/kube-prometheus.libsonnet') + {
     _config+:: {
       namespace: 'monitoring',
     },
+
+    grafana+: {
+      service+: service.mixin.metadata.withAnnotations({
+        'external-dns.alpha.kubernetes.io/hostname': 'my-hostname',
+      }),
+    },
   };
 
{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['prometheus-adapter-' + name]: kp.prometheusAdapter[name] for name in std.objectFields(kp.prometheusAdapter) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Comment by jpc2350** [comment]
Hi @metalmatze, 
Apologies, but thanks!
