### ISSUE TITLE
Additional datasources

### ISSUE THREAD

**Issue by e9169** [brancz/kubernetes-grafana#71]
Hi,

Looking at the code in grafana.libsonnet I'm wondering how we could/should add a new datasource to be populated into grafana. Currently we have:

  grafana+:: {
      dashboards: {},
      datasources: [{
        name: 'prometheus',
        type: 'prometheus',
        access: 'proxy',
        orgId: 1,
        url: 'http://prometheus-k8s.' + $._config.namespace + '.svc:9090',
        version: 1,
        editable: false,
      }],
      config: {},
      ldap: null,
      plugins: [],
    },

I guess it should be somewhere inside the [ in datasources section but I'm not sure how to specifiy both of them (prometheus and the new one).

Thanks!

**Comment by brancz** [comment]
Are you looking for something like this?

```jsonnet
{
  grafana+:: {
    datasources+: [
      {
        // your additional datasource
      },
    ],
  },
}
```

If so, do you want to add some docs on an example? :)

**Comment by e9169** [comment]
> Are you looking for something like this?
> 
> ```jsonnet
> {
>   grafana+:: {
>     datasources+: [
>       {
>         // your additional datasource
>       },
>     ],
>   },
> }
> ```
> 
> If so, do you want to add some docs on an example? :)

Yes, the idea is to have more than just prometheus as datasource. In fact, we want to add thanos-query as datasource, but I just don't know how to specify two (or more) in the lines you wrote, yes. 

```jsonnet
{
   grafana+:: {
   datasources+: [
       {
         // prometheus datasource
       },
       {
        // thanos-query datasource
       },
   ],
   },
 }
```
Does this look okay from a syntax point of view?

Thanks!

**Comment by brancz** [comment]
In jsonnet when you do `+: [ ... ]` it will append the entries that you specify, so while your example above looks right syntax wise, the result will be the default prometheus data source, your explicit prometheus datasource and your explicit thanos-query datasource. If you don't care about the default datasource, then just remove the `+` from that snippet after the `datasources` key, and the whole array will be replaced with your array.

**Comment by e9169** [comment]
Thank you very much @brancz
