### ISSUE TITLE
examples/dashboard-definition.jsonnet dashboardDefinitions is emtpy 

### ISSUE THREAD

**Issue by liuyangc3** [brancz/kubernetes-grafana#86]
I run dashboard-definition.jsonnet  on my mac, result of dashboardDefinitions is `[]`

I found the addTemplate here is different from grafonnet-lib [example](https://github.com/grafana/grafonnet-lib/blob/master/examples/prometheus.jsonnet#L67)
```jsonnet
// line 21
             dashboard.new('My Dashboard')
             .addTemplate(..)
```

and many projects use this libs `grafana-builder/grafana.libsonnet` to build grafana dashboard,  what is the difference between grafana-builder and grafonnet-lib?

**Comment by brancz** [comment]
They just take different approaches at a library for building grafana dashboards in jsonnet. As with many thing, some prefer one, some prefer the other library :)
