### ISSUE TITLE
Organisation home dashboard?

### ISSUE THREAD

**Issue by GTB3NW** [brancz/kubernetes-grafana#87]
Hey, is it possible to set the home dashboard for an organisation within this mixin?

Cheers!

**Comment by brancz** [comment]
Dashboard definitions are generally a non goal of this project, but I’m still interested in what you would want to see on a dashboard like that? Maybe it can fit into another existing project.

**Comment by GTB3NW** [comment]
It's less the creation of said dashboard, more the setting of it. In grafana if you go the org settings, you can set the home dashboard for the org if you have starred another dashboard. It obviously doesn't persist those settings, so it would be good to set that programatically if possible?

My personal use case would be to have a dashboard which the owners can look at without having to go through menus (or bookmarks)

**Comment by brancz** [comment]
Ah! That makes a lot of sense. Are you aware of a flag or file configuration that allows you to do this in grafana?

**Comment by GTB3NW** [comment]
No idea sorry, I think this probably would require upstream changes unless they allow org dashboards

**Comment by brancz** [comment]
That would be a question to Grafana folks. Maybe @bergquist knows? :)

**Comment by bergquist** [comment]
@brancz are you stalking me or is this just a coincident? :) https://github.com/grafana/grafana/issues/25463

**Comment by brancz** [comment]
Hahahahahaha I promise this is a coincidence, but a very awesome one! :)

@GTB3NW are you ok with closing this issue in favor of the upstream Grafana one? It's already possible to configure arbitrary `grafana.ini` configurations in this project so as soon as it's available in Grafana it will be possible with this project.

**Comment by GTB3NW** [comment]
> Hahahahahaha I promise this is a coincidence, but a very awesome one! :)
> 
> @GTB3NW are you ok with closing this issue in favor of the upstream Grafana one? It's already possible to configure arbitrary `grafana.ini` configurations in this project so as soon as it's available in Grafana it will be possible with this project.

Only if you promise to stop stalking @bergquist :P
