### ISSUE TITLE
Grafana HA and stateless with authentication possible?

### ISSUE THREAD

**Issue by maxbrunet** [brancz/kubernetes-grafana#89]
The README states:

> This allows easily operating Grafana highly available as if it was a stateless application - no need to run a clustered database for your dashboarding solution anymore!

But with multiple replicas, I found that I need to re-authenticate to each of them.

So I would like to know what is your approach to scale Grafana horizontally and avoid downtime during restarts?

---

A few things I have tried without luck:

### Remote cache

https://grafana.com/docs/grafana/latest/administration/configuration/#remote_cache

```ini
[remote_cache]
type = memcached
connstr = grafana-memcached-0.grafana-memcached:11211
```

But apparently, this is not used to store sessions 😞: https://github.com/grafana/grafana/issues/25735#issuecomment-647723398

### Oauth auto login

We use Google OAuth, so I thought Grafana could just validate this.

https://grafana.com/docs/grafana/latest/administration/configuration/#oauth_auto_login

```ini
[auth]
oauth_auto_login = true
[auth.google]
enabled = true
allow_sign_up = true
client_id = <REDACTED>
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
token_url = https://accounts.google.com/o/oauth2/token
[server]
root_url = <REDACTED>
```

This goes into a redirect loop between Grafana and Google.

---

I see LDAP is supported, is there something different about it?

The last option, I have thought about is disabling authentication on Grafana and using https://github.com/oauth2-proxy/oauth2-proxy in front of it.

**Comment by brancz** [comment]
> The last option, I have thought about is disabling authentication on Grafana and using https://github.com/oauth2-proxy/oauth2-proxy in front of it.

For what it's worth, this is what I/we do.

**Comment by maxbrunet** [comment]
Thank you @brancz for your reply and this nice library, it makes sense to me now, Grafana apparently signs up users (including creating IDs for them) in its database even with an identity provider. I will not bother the Grafana folks, I just wanted to make sure I was not missing something. I will deploy the OAuth proxy in front of it, and if that works, I will close this issue. Thanks again.

**Comment by maxbrunet** [comment]
So far, so good
